stashSettings:

  # Occurs during initialization |  Immutable
  cleanStash: 
    name: CleanStash

  # Include either the Source folder or the workspace defined in the config.yaml
  source: 
    name: Source
    includes: "Source/**, source/**, src/**"
    excludes:
      default:
        - "**/*~, **/#*#, **/.#*, **/%*%, **/._*"
        - "**/CVS, **/CVS/**, **/.cvsignore"
        - "**/SCCS, **/SCCS/**, **/vssver.scc"
        - "**/.svn, **/.svn/**"
        - "**/.DS_Store"
        #- "**/.git, **/.git/**, **/.gitattributes, **/.gitignore, **/.gitmodules"
        - "**/.hg, **/.hg/**, **/.hgignore, **/.hgsub, **/.hgsubstate, **/.hgtags"
        - "**/.bzr, **/.bzr/**, **/.bzrignore"
      nodejs:
        - ".cache/**, **/node_modules/**, README.md"

  DB: 
    name: DB
    includes: "DB/**, db/**"
    # excludes: ".org.zeron.pipeline/**"
  
  orchestration: 
    name: Orchestration
    includes: "Orchestration/**, orchestration/**"
    # excludes: ".org.zeron.pipeline/**"

  # Stashes the build output defined in the config.yaml | Immutable
  buildOutput:
    name: AppBuildOutput

  # Stashes the application build package | generated by the pipeline | Immutable
  appBuildArtifact: 
    name: AppBuildStash

  # Stashes the DB build package | generated by the pipeline | Immutable
  dbBuildArtifact: 
    name: DBBuildStash

  # Stashes generated CAST Reports | Immutable
  castReports:
    name: castReports
    includes: '**/CAST-Reports/**'

  # Holds logs across different stages/tools for notification attachement
  notificationAttachments:
    castScan:
      name: 'castScanLogs'
    deliver:
      name: 'deliverLogs'
    deploy:
      name: 'deployLogs'
