// #!/usr/bin/env groovy
// @Library('test-shared-library') _
// zeronPipeline script:this

pieline {
  agent any
  stages {
    stage('Hello') {
      steps {
        sh 'echo Hello World'
        echo "Build Number is ${currentBuild.number}"
      }
    }
  }
}
