   // #!/usr/bin/env groovy
// @Library('test-shared-library') _
// zeronPipeline script:this

pipeline {
  agent any
  stages {
    stage('Hello') {
      steps {
        bat 'echo Hello World'
        echo "Build Number is ${currentBuild.rawBuild}"
        script {
           def parameterName = 'group'
           
           def build = currentBuild.rawBuild
           def parametersAction = build.getAction(ParametersAction)
           def parameterValue = null

           if (parametersAction) {
              def parameters = parametersAction.parameters
              echo "Parameters is ${parameters}"
              parameters.each { param ->
                 if (param.name == parameterName) {
                    parameterValue = param.value.toString()
                    echo "Group Parameter Value is ${parameterValue}"
                 }
           }
        }
      }
    }
  }
}
